PKG_NAME=reactor-uc
PKG_URL=https://github.com/erlingrj/reactor-uc.git
PKG_VERSION=a687b897f94c24415a8194b52d77dea536ae3361
PKG_LICENSE=BSD

include $(RIOTBASE)/pkg/pkg.mk

all:
	$(QQ)"$(MAKE)" -C $(PKG_SOURCE_DIR)/src -f $(CURDIR)/$(PKG_NAME).mk
