PKG_NAME=reactor-uc
PKG_URL=https://github.com/tanneberger/reactor-uc.git
PKG_VERSION=458d74fd6353172a3fc5c750e0dbc733477b0f4a
PKG_LICENSE=BSD

include $(RIOTBASE)/pkg/pkg.mk

all:
	$(QQ)"$(MAKE)" -C $(PKG_SOURCE_DIR)/src -f $(CURDIR)/$(PKG_NAME).mk
