PKG_NAME=reactor-uc
PKG_URL=https://github.com/erlingrj/reactor-uc.git
PKG_VERSION=4c6f0ab279c7250cebc9b5168c4fcbd7664e4714
PKG_LICENSE=BSD

include $(RIOTBASE)/pkg/pkg.mk

all:
	$(QQ)"$(MAKE)" -C $(PKG_SOURCE_DIR)/src -f $(CURDIR)/$(PKG_NAME).mk
